"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "ta" | "hi";

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Topbar & Navigation
    "nav.brand": "TrustMed-AI",
    "nav.brandSubtitle": "Clinical Decision Support System",
    "nav.pipeline": "Doctor CDSS Workflow",
    "nav.benchmarks": "Report Ingestion & OCR",
    "nav.vitals": "AI Risk Modeling",
    "nav.xai": "SHAP Biomarker Explanations",
    "nav.blockchain": "Blockchain Audit Proofs",
    "nav.aiSummary": "AI Clinical Summary",
    "nav.profile": "Doctor Credentials & NPI",
    "nav.summary": "Executive Summary",
    "nav.tamperVerification": "Tamper Verification",
    "nav.cohort": "Cohort Population",
    "nav.settings": "System Settings",
    "nav.logout": "Sign Out",
    "nav.patient": "Doctor CDSS",
    "nav.doctor": "Doctor Portal",
    "nav.admin": "System Administrator",
    "nav.activeAccount": "Active Clinician Session",
    "nav.searchPlaceholder": "Search biomarkers, records, or tx hash...",

    // Common
    "common.language": "Language",
    "common.english": "English",
    "common.tamil": "தமிழ் (Tamil)",
    "common.hindi": "हिन्दी (Hindi)",
    "common.save": "Save Changes",
    "common.cancel": "Cancel",
    "common.loading": "Loading...",
    "common.verified": "Verified",
    "common.optimal": "OPTIMAL",
    "common.elevated": "ELEVATED",
    "common.critical": "CRITICAL",
    "common.highRisk": "High Risk",
    "common.lowRisk": "Low Risk",
    "common.moderateRisk": "Moderate Risk",

    // Landing Page
    "landing.badge": "Blockchain-Anchored Explainable AI Clinical Decision Support",
    "landing.heroTitle": "Blockchain-Enabled Explainable AI for Specific Disease Risk Prediction",
    "landing.heroSubtitle": "Dual-ensemble machine learning with local SHAP & LIME biomarker attributions, optical document lab report ingestion, and tamper-proof blockchain audit trails.",
    "landing.getStarted": "Launch Doctor CDSS Portal",
    "landing.adminLogin": "System Administrator Login",
    "landing.feature1Title": "Optical Lab Ingestion & Benchmarks",
    "landing.feature1Desc": "Upload PDF and scanned medical reports with instant ADA, AHA, and WHO clinical benchmark evaluations.",
    "landing.feature2Title": "Dual-Ensemble ML Intelligence",
    "landing.feature2Desc": "XGBoost and Random Forest models bounded by SecRE physiological safety invariants.",
    "landing.feature3Title": "Cryptographic Audit Ledger",
    "landing.feature3Desc": "Immutable EVM smart contract record anchoring ensuring zero data tampering.",

    // Auth
    "auth.signIn": "Doctor Sign In",
    "auth.signUp": "Clinician Registration",
    "auth.adminPortal": "Admin Portal",
    "auth.phone": "Phone Number or Email",
    "auth.password": "Password",
    "auth.loginBtn": "Sign In to Doctor Portal",
    "auth.registerBtn": "Complete Clinician Registration",
    "auth.firstName": "First Name",
    "auth.lastName": "Last Name",
    "auth.age": "Age (Years)",
    "auth.gender": "Biological Gender",
    "auth.address": "City / Hospital Address",
    "auth.role": "Account Role",
    "auth.autoGeneratedNotice": "Clinician Identifier and Clinical Record Number will be configured upon registration.",

    // Report Benchmarker
    "report.title": "Medical Report Ingestion, Interactive Verification & Benchmarks",
    "report.subtitle": "Upload patient clinical lab reports (PDF or scan). The optical entity extractor automatically identifies physiological biomarkers with high-precision confidence scoring and computes clinical benchmarks (ADA, AHA, WHO, NCEP).",
    "report.dropzoneText": "Click or drag medical report file here",
    "report.dropzoneSub": "Supports standard laboratory PDFs, hospital image scans (PNG, JPG, TIFF)",
    "report.runOcr": "Run High-Precision OCR & Benchmark Analysis",
    "report.highRiskSample": "High-Risk Lab (PDF)",
    "report.healthySample": "Healthy Baseline (PDF)",
    "report.step2Title": "Step 2: Interactive Clinical Attribute Verification",
    "report.step2Sub": "Review the extracted values. If any biomarker is slightly off or needs clinical modification, edit the value directly below.",
    "report.compositeIndex": "Composite Health Index",
    "report.submitToAi": "Submit Verified Values to AI Assessment Engine",
    "report.glucose": "Fasting Glucose",
    "report.bp": "Systolic BP",
    "report.bmi": "Body Mass Index",
    "report.cholesterol": "Total Cholesterol",
    "report.insulin": "Fasting Insulin",
    "report.heartRate": "Resting Heart Rate",
    "report.ageField": "Age",
    "report.benchmarksTitle": "Clinical Standard Benchmarks & Regulatory Classifications",

    // Risk Predictor
    "predictor.title": "Patient Physiological Vitals & AI Diagnostic Assessment",
    "predictor.subtitle": "Run dual-ensemble ML inference with strict physiological invariant checks and compute local explainability.",
    "predictor.runBtn": "Run SecRE-XAI Diagnostic Risk Inference",
    "predictor.anchorBtn": "Anchor Verified Record to Blockchain",
    "predictor.model": "Diagnostic Model",
    "predictor.resultTitle": "Diagnostic Risk Assessment Result",
    "predictor.riskScore": "Predicted Risk Probability",
    "predictor.securityRate": "SecRE Security Rate (SR)",
    "predictor.explainabilityRate": "Explainability Rate (ER)",
    "predictor.anchored": "Anchored On-Chain",

    // XAI
    "xai.title": "Biomarker Impact & Feature Explanations",
    "xai.subtitle": "Local SHAP and LIME feature attributions quantify the exact contribution of each biomarker to the clinical risk prediction.",
    "xai.increaseRisk": "Increases Risk",
    "xai.decreasesRisk": "Protective / Lowers Risk",

    // Tamper Check
    "tamper.title": "1-Click Cryptographic Tamper & Integrity Verification",
    "tamper.subtitle": "Verify the mathematical authenticity of clinical diagnostic records against the Ethereum smart contract ledger.",
    "tamper.verifyBtn": "Verify Integrity Against Smart Contract",
    "tamper.statusValid": "AUTHENTIC & UNTAMPERED",
    "tamper.statusTampered": "TAMPERING DETECTED",

    // Profile
    "profile.title": "My Patient Credentials & Medical Identity Card",
    "profile.patientId": "Patient Identifier",
    "profile.recordNo": "Clinical Record Number",
    "profile.phone": "Registered Phone",
    "profile.email": "Email Address",
    "profile.ageGender": "Age / Gender",
    "profile.wallet": "EVM Signer Wallet Address",
    "profile.generateCert": "Generate Verifiable Certificate",

    // AI Summary
    "summary.title": "AI Clinical Executive Synthesizer & Copilot",
    "summary.subtitle": "Multi-modal diagnostic synthesis and interactive CDSS assistant.",
    "summary.generate": "Generate AI Clinical Synthesis",
    "summary.chatPrompt": "Ask SecRE-XAI Copilot...",
    "summary.send": "Send Query",
  },

  ta: {
    // Topbar & Navigation
    "nav.brand": "டிரஸ்ட்மெட்-AI (TrustMed)",
    "nav.brandSubtitle": "மருத்துவ முடிவு ஆதரவு அமைப்பு",
    "nav.benchmarks": "அறிக்கை பதிவேற்றம் & தரநிலைகள்",
    "nav.vitals": "நோயாளி முக்கிய அளவுகள் & AI இடர்",
    "nav.xai": "உயிர் குறிப்பான் விளக்கங்கள்",
    "nav.blockchain": "பிளாக்செயின் தணிக்கை சான்றுகள்",
    "nav.aiSummary": "AI மருத்துவ சுருக்கம்",
    "nav.profile": "எனது நோயாளி சான்றுகள்",
    "nav.summary": "நிர்வாக சுருக்கம்",
    "nav.tamperVerification": "முறைகேடு சரிபார்ப்பு",
    "nav.cohort": "மக்கள் தொகை குழு",
    "nav.settings": "கணினி அமைப்புகள்",
    "nav.logout": "வெளியேறு",
    "nav.patient": "நோயாளி",
    "nav.admin": "கணினி நிர்வாகி",
    "nav.activeAccount": "செயலில் உள்ள கணக்கு",
    "nav.searchPlaceholder": "உயிர் குறிப்பான்கள், பதிவுகள் அல்லது முகவரியைத் தேடுங்கள்...",

    // Common
    "common.language": "மொழி",
    "common.english": "English",
    "common.tamil": "தமிழ் (Tamil)",
    "common.hindi": "हिन्दी (Hindi)",
    "common.save": "மாற்றங்களைச் சேமி",
    "common.cancel": "ரத்து செய்",
    "common.loading": "ஏற்றுகிறது...",
    "common.verified": "சரிபார்க்கப்பட்டது",
    "common.optimal": "சிறந்தது (Optimal)",
    "common.elevated": "அதிகரித்தது (Elevated)",
    "common.critical": "முக்கியமானது (Critical)",
    "common.highRisk": "அதிக ஆபத்து",
    "common.lowRisk": "குறைந்த ஆபத்து",
    "common.moderateRisk": "மிதமான ஆபத்து",

    // Landing Page
    "landing.badge": "SecRE-XAI சான்றளிக்கப்பட்டது & எத்தேரியம் இணைக்கப்பட்டது",
    "landing.heroTitle": "மருத்துவ இடர் நுண்ணறிவுக்கான சரிபார்க்கக்கூடிய விளக்க AI",
    "landing.heroSubtitle": "SHAP & LIME உயிர் குறிப்பான் பண்புக்கூறுகள், மருத்துவ ஆய்வக அறிக்கை பிரித்தெடுத்தல் மற்றும் மாற்ற முடியாத பிளாக்செயின் தணிக்கை சுவடுகள் கொண்ட இரட்டை இயந்திர கற்றல்.",
    "landing.getStarted": "மருத்துவ போர்ட்டலைத் தொடங்குங்கள்",
    "landing.adminLogin": "நிர்வாகி உள்நுழைவு",
    "landing.feature1Title": "ஆய்வக அறிக்கை ஆய்வு & தரநிலைகள்",
    "landing.feature1Desc": "ADA, AHA மற்றும் WHO மருத்துவ தரநிலை மதிப்பீடுகளுடன் PDF மற்றும் ஸ்கேன் செய்யப்பட்ட அறிக்கைகளை பதிவேற்றவும்.",
    "landing.feature2Title": "இரட்டை இயந்திர கற்றல் நுண்ணறிவு",
    "landing.feature2Desc": "உடலியல் பாதுகாப்பு விதிகளால் கட்டுப்படுத்தப்படும் XGBoost மற்றும் Random Forest மாதிரிகள்.",
    "landing.feature3Title": "பிளாக்செயின் தணிக்கை பதிவேடு",
    "landing.feature3Desc": "தரவு மாற்ற முடியாத வகையில் ஸ்மார்ட் ஒப்பந்தத்தில் பதிவு செய்யப்படும் பாதுகாப்பு.",

    // Auth
    "auth.signIn": "உள்நுழைய",
    "auth.signUp": "நோயாளி பதிவு",
    "auth.adminPortal": "நிர்வாக போர்டல்",
    "auth.phone": "தொலைபேசி எண்",
    "auth.password": "கடவுச்சொல்",
    "auth.loginBtn": "மருத்துவ போர்ட்டலில் உள்நுழையவும்",
    "auth.registerBtn": "நோயாளி பதிவை முடிக்கவும்",
    "auth.firstName": "முதல் பெயர்",
    "auth.lastName": "கடைசி பெயர்",
    "auth.age": "வயது (ஆண்டுகள்)",
    "auth.gender": "பாலினம்",
    "auth.address": "முகவரி / நகரம்",
    "auth.role": "கணக்கு பங்கு",
    "auth.autoGeneratedNotice": "பதிவு செய்யும் போது நோயாளி ஐடி (PAT-2026-XXXX) மற்றும் மருத்துவ பதிவு எண் (REC-XXXXX) தானாக உருவாக்கப்படும்.",

    // Report Benchmarker
    "report.title": "மருத்துவ அறிக்கை பதிவேற்றம், ஊடாடும் சரிபார்ப்பு & தரநிலைகள்",
    "report.subtitle": "நோயாளி ஆய்வக அறிக்கைகளை (PDF அல்லது ஸ்கேன்) பதிவேற்றவும். ஆக்ஸ்போர்டு OCR எஞ்சின் உயிர் குறிப்பான்களைத் துல்லியமாக பிரித்தெடுத்து ADA, AHA, WHO தரநிலைகளுடன் ஒப்பிடுகிறது.",
    "report.dropzoneText": "மருத்துவ அறிக்கை கோப்பை இங்கே கிளிக் செய்யவும் அல்லது இழுத்து விடவும்",
    "report.dropzoneSub": "நிலையான ஆய்வக PDF மற்றும் மருத்துவ படங்களை (PNG, JPG, TIFF) ஆதரிக்கிறது",
    "report.runOcr": "உயர் துல்லிய OCR & தரநிலை பகுப்பாய்வை இயக்கவும்",
    "report.highRiskSample": "அதிக ஆபத்து அறிக்கை (PDF)",
    "report.healthySample": "ஆரோக்கியமான அறிக்கை (PDF)",
    "report.step2Title": "படி 2: ஊடாடும் மருத்துவ அளவுரு சரிபார்ப்பு",
    "report.step2Sub": "பிரித்தெடுக்கப்பட்ட மதிப்புகளை மதிப்பாய்வு செய்யவும். ஏதேனும் மதிப்பு மாறினால், அதை கீழே நேரடியாக திருத்தலாம்.",
    "report.compositeIndex": "கூட்டு சுகாதார குறியீடு",
    "report.submitToAi": "சரிபார்க்கப்பட்ட மதிப்புகளை AI இயந்திரத்திற்கு சமர்ப்பிக்கவும்",
    "report.glucose": "இரத்த சர்க்கரை (Glucose)",
    "report.bp": "இரத்த அழுத்தம் (Systolic BP)",
    "report.bmi": "உடல் நிறை குறியீடு (BMI)",
    "report.cholesterol": "மொத்த கொழுப்பு (Cholesterol)",
    "report.insulin": "இன்சுலின் அளவு (Insulin)",
    "report.heartRate": "இதய துடிப்பு (Heart Rate)",
    "report.ageField": "வயது",
    "report.benchmarksTitle": "மருத்துவ தரநிலைகள் & சர்வதேச வகைப்பாடுகள்",

    // Risk Predictor
    "predictor.title": "நோயாளி முக்கிய அளவுகள் & AI மருத்துவ இடர் மதிப்பீடு",
    "predictor.subtitle": "உடலியல் பாதுகாப்பு விதிகளுடன் கூடிய AI மதிப்பீட்டை இயக்கி காரணிகளை பகுப்பாய்வு செய்யவும்.",
    "predictor.runBtn": "SecRE-XAI இடர் மதிப்பீட்டை இயக்கவும்",
    "predictor.anchorBtn": "பிளாக்செயினில் பதிவை பாதுகாக்கவும்",
    "predictor.model": "கண்டறியும் மாதிரி",
    "predictor.resultTitle": "மருத்துவ இடர் மதிப்பீட்டு முடிவு",
    "predictor.riskScore": "கணிக்கப்பட்ட இடர் நிகழ்தகவு",
    "predictor.securityRate": "SecRE பாதுகாப்பு விகிதம் (SR)",
    "predictor.explainabilityRate": "விளக்கக்கூடிய விகிதம் (ER)",
    "predictor.anchored": "பிளாக்செயினில் பதிவு செய்யப்பட்டது",

    // XAI
    "xai.title": "உயிர் குறிப்பான் தாக்கம் & அம்ச விளக்கங்கள்",
    "xai.subtitle": "SHAP மற்றும் LIME விளக்கங்கள் ஒவ்வொரு உயிர் குறிப்பானும் மருத்துவ இடருக்கு எவ்வாறு பங்களிக்கிறது என்பதை அளவிடுகின்றன.",
    "xai.increaseRisk": "ஆபத்தை அதிகரிக்கிறது",
    "xai.decreasesRisk": "பாதுகாப்பானது / ஆபத்தை குறைக்கிறது",

    // Tamper Check
    "tamper.title": "1-கிளிக் கிரிப்டோகிராஃபிக் முறைகேடு சரிபார்ப்பு",
    "tamper.subtitle": "எத்தேரியம் ஸ்மார்ட் ஒப்பந்தத்தில் மருத்துவ பதிவுகளின் உண்மைத்தன்மையை சரிபார்க்கவும்.",
    "tamper.verifyBtn": "ஸ்மார்ட் ஒப்பந்தத்திற்கு எதிராக சரிபார்க்கவும்",
    "tamper.statusValid": "உண்மையானது & மாற்றப்படாதது",
    "tamper.statusTampered": "முறைகேடு கண்டறியப்பட்டது",

    // Profile
    "profile.title": "எனது நோயாளி சான்றுகள் & மருத்துவ அடையாள அட்டை",
    "profile.patientId": "நோயாளி அடையாள எண்",
    "profile.recordNo": "மருத்துவ பதிவு எண்",
    "profile.phone": "பதிவு செய்யப்பட்ட தொலைபேசி",
    "profile.email": "மின்னஞ்சல் முகவரி",
    "profile.ageGender": "வயது / பாலினம்",
    "profile.wallet": "EVM வாலட் முகவரி",
    "profile.generateCert": "சரிபார்க்கக்கூடிய சான்றிதழை உருவாக்கவும்",

    // AI Summary
    "summary.title": "AI மருத்துவ நிர்வாக சுருக்கம் & உதவியாளர்",
    "summary.subtitle": "பல மாதிரி மருத்துவ சுருக்கம் மற்றும் ஊடாடும் AI உதவியாளர்.",
    "summary.generate": "AI மருத்துவ சுருக்கத்தை உருவாக்கவும்",
    "summary.chatPrompt": "மருத்துவ உதவியாளரிடம் கேளுங்கள்...",
    "summary.send": "கேள்வியை அனுப்பு",
  },

  hi: {
    // Topbar & Navigation
    "nav.brand": "ट्रस्टमेड-AI (TrustMed)",
    "nav.brandSubtitle": "क्लिनिकल निर्णय सहायता प्रणाली",
    "nav.benchmarks": "रिपोर्ट अपलोड और मानक",
    "nav.vitals": "रोगी महत्वपूर्ण लक्षण और AI जोखिम",
    "nav.xai": "बायोमार्कर स्पष्टीकरण",
    "nav.blockchain": "ब्लॉकचेन ऑडिट प्रमाण",
    "nav.aiSummary": "AI क्लिनिकल सारांश",
    "nav.profile": "मेरे रोगी क्रेडेंशियल",
    "nav.summary": "कार्यकारी सारांश",
    "nav.tamperVerification": "छेड़छाड़ सत्यापन",
    "nav.cohort": "जनसंख्या समूह",
    "nav.settings": "सिस्टम सेटिंग्स",
    "nav.logout": "लॉग आउट",
    "nav.patient": "रोगी",
    "nav.admin": "सिस्टम व्यवस्थापक",
    "nav.activeAccount": "सक्रिय खाता",
    "nav.searchPlaceholder": "बायोमार्कर, रिकॉर्ड या हैश खोजें...",

    // Common
    "common.language": "भाषा",
    "common.english": "English",
    "common.tamil": "தமிழ் (Tamil)",
    "common.hindi": "हिन्दी (Hindi)",
    "common.save": "परिवर्तन सहेजें",
    "common.cancel": "रद्द करें",
    "common.loading": "लोड हो रहा है...",
    "common.verified": "सत्यापित",
    "common.optimal": "उत्कृष्ट (Optimal)",
    "common.elevated": "बढ़ा हुआ (Elevated)",
    "common.critical": "गंभीर (Critical)",
    "common.highRisk": "उच्च जोखिम",
    "common.lowRisk": "कम जोखिम",
    "common.moderateRisk": "मध्यम जोखिम",

    // Landing Page
    "landing.badge": "SecRE-XAI प्रमाणित और एथेरियम पर सुरक्षित",
    "landing.heroTitle": "नैदानिक जोखिम विश्लेषण के लिए सत्यापन योग्य व्याख्यात्मक AI",
    "landing.heroSubtitle": "स्थानीय SHAP और LIME बायोमार्कर विश्लेषण, लैब रिपोर्ट निष्कर्षण और अपरिवर्तनीय ब्लॉकचेन ऑडिट के साथ उन्नत मशीन लर्निंग।",
    "landing.getStarted": "क्लिनिकल पोर्टल शुरू करें",
    "landing.adminLogin": "व्यवस्थापक लॉगिन",
    "landing.feature1Title": "लैब रिपोर्ट निष्कर्षण और मानक",
    "landing.feature1Desc": "ADA, AHA और WHO क्लिनिकल बेंचमार्क मूल्यांकन के साथ PDF और स्कैन की गई रिपोर्ट अपलोड करें।",
    "landing.feature2Title": "उन्नत मशीन लर्निंग बुद्धिमत्ता",
    "landing.feature2Desc": "शारीरिक सुरक्षा नियमों द्वारा नियंत्रित XGBoost और Random Forest मॉडल।",
    "landing.feature3Title": "ब्लॉकचेन ऑडिट लेजर",
    "landing.feature3Desc": "डेटा की अखंडता सुनिश्चित करने वाला स्मार्ट अनुबंध पर सुरक्षित रिकॉर्ड।",

    // Auth
    "auth.signIn": "साइन इन करें",
    "auth.signUp": "रोगी पंजीकरण",
    "auth.adminPortal": "व्यवस्थापक पोर्टल",
    "auth.phone": "फ़ोन नंबर",
    "auth.password": "पासवर्ड",
    "auth.loginBtn": "हेल्थ पोर्टल में साइन इन करें",
    "auth.registerBtn": "रोगी पंजीकरण पूरा करें",
    "auth.firstName": "पहला नाम",
    "auth.lastName": "अंतिम नाम",
    "auth.age": "आयु (वर्ष)",
    "auth.gender": "लिंग",
    "auth.address": "पता / शहर",
    "auth.role": "खाता भूमिका",
    "auth.autoGeneratedNotice": "पंजीकरण पर रोगी आईडी (PAT-2026-XXXX) और क्लिनिकल रिकॉर्ड नंबर (REC-XXXXX) स्वचालित रूप से जनरेट होंगे।",

    // Report Benchmarker
    "report.title": "चिकित्सा रिपोर्ट अपलोड, इंटरएक्टिव सत्यापन और मानक",
    "report.subtitle": "रोगी लैब रिपोर्ट (PDF या स्कैन) अपलोड करें। OCR इंजन स्वचालित रूप से बायोमार्कर निकालता है और ADA, AHA, WHO मानकों के साथ मूल्यांकन करता है।",
    "report.dropzoneText": "चिकित्सा रिपोर्ट फ़ाइल यहाँ क्लिक करें या खींचें",
    "report.dropzoneSub": "मानक प्रयोगशाला PDF और अस्पताल इमेज स्कैन (PNG, JPG, TIFF) समर्थित हैं",
    "report.runOcr": "उच्च-सटीक OCR और बेंचमार्क विश्लेषण चलाएं",
    "report.highRiskSample": "उच्च जोखिम लैब (PDF)",
    "report.healthySample": "स्वस्थ बेसलाइन (PDF)",
    "report.step2Title": "चरण 2: इंटरएक्टिव क्लिनिकल सत्यापन",
    "report.step2Sub": "निकाले गए मानों की समीक्षा करें। यदि कोई मान बदलना है, तो सीधे नीचे संपादित करें।",
    "report.compositeIndex": "समग्र स्वास्थ्य सूचकांक",
    "report.submitToAi": "सत्यापित मान AI इंजन में सबमिट करें",
    "report.glucose": "रक्त शर्करा (Glucose)",
    "report.bp": "रक्तचाप (Systolic BP)",
    "report.bmi": "बॉडी मास इंडेक्स (BMI)",
    "report.cholesterol": "कुल कोलेस्ट्रॉल (Cholesterol)",
    "report.insulin": "इंसुलिन स्तर (Insulin)",
    "report.heartRate": "हृदय गति (Heart Rate)",
    "report.ageField": "आयु",
    "report.benchmarksTitle": "क्लिनिकल मानक और नियामक वर्गीकरण",

    // Risk Predictor
    "predictor.title": "रोगी महत्वपूर्ण लक्षण और AI नैदानिक जोखिम मूल्यांकन",
    "predictor.subtitle": "शारीरिक सुरक्षा नियमों के साथ AI अनुमान चलाएं और बायोमार्कर प्रभाव का विश्लेषण करें।",
    "predictor.runBtn": "SecRE-XAI नैदानिक जोखिम अनुमान चलाएं",
    "predictor.anchorBtn": "ब्लॉकचेन पर रिकॉर्ड सुरक्षित करें",
    "predictor.model": "नैदानिक मॉडल",
    "predictor.resultTitle": "नैदानिक जोखिम मूल्यांकन परिणाम",
    "predictor.riskScore": "अनुमानित जोखिम संभावना",
    "predictor.securityRate": "SecRE सुरक्षा दर (SR)",
    "predictor.explainabilityRate": "व्याख्यात्मक दर (ER)",
    "predictor.anchored": "ब्लॉकचेन पर सुरक्षित",

    // XAI
    "xai.title": "बायोमार्कर प्रभाव और विशेषता स्पष्टीकरण",
    "xai.subtitle": "SHAP और LIME स्पष्टीकरण यह मापते हैं कि प्रत्येक बायोमार्कर नैदानिक जोखिम में कितना योगदान देता है।",
    "xai.increaseRisk": "जोखिम बढ़ाता है",
    "xai.decreasesRisk": "सुरक्षात्मक / जोखिम कम करता है",

    // Tamper Check
    "tamper.title": "1-क्लिक क्रिप्टोग्राफ़िक छेड़छाड़ सत्यापन",
    "tamper.subtitle": "एथेरियम स्मार्ट अनुबंध के विरुद्ध चिकित्सा रिकॉर्ड की प्रामाणिकता की जाँच करें।",
    "tamper.verifyBtn": "स्मार्ट अनुबंध के विरुद्ध सत्यापित करें",
    "tamper.statusValid": "प्रामाणिक और अपरिवर्तित",
    "tamper.statusTampered": "छेड़छाड़ का पता चला",

    // Profile
    "profile.title": "मेरे रोगी क्रेडेंशियल और चिकित्सा पहचान पत्र",
    "profile.patientId": "रोगी पहचान संख्या",
    "profile.recordNo": "क्लिनिकल रिकॉर्ड नंबर",
    "profile.phone": "पंजीकृत फ़ोन",
    "profile.email": "ईमेल पता",
    "profile.ageGender": "आयु / लिंग",
    "profile.wallet": "EVM वॉलेट पता",
    "profile.generateCert": "सत्यापन योग्य प्रमाणपत्र जनरेट करें",

    // AI Summary
    "summary.title": "AI क्लिनिकल सारांश और सहायक",
    "summary.subtitle": "मल्टी-मॉडल डायग्नोस्टिक सारांश और इंटरएक्टिव AI सहायक।",
    "summary.generate": "AI क्लिनिकल सारांश जनरेट करें",
    "summary.chatPrompt": "क्लिनिकल सहायक से पूछें...",
    "summary.send": "प्रश्न भेजें",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string, fallback?: string) => fallback || key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    try {
      const saved = localStorage.getItem("trustmed_language") as Language;
      if (saved && (saved === "en" || saved === "ta" || saved === "hi")) {
        setLanguageState(saved);
      }
    } catch {
      // localStorage not accessible
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("trustmed_language", lang);
    } catch {
      // Ignore
    }
  };

  const t = (key: string, fallback?: string): string => {
    const dict = translations[language] || translations.en;
    if (dict[key]) {
      return dict[key];
    }
    const enDict = translations.en;
    if (enDict[key]) {
      return enDict[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
